/**
 * Lead Capture API Route
 * Handles popup form submissions (exit-intent, free audit, etc.)
 *
 * - Validates lead data (email, firstName, company)
 * - Sends notification email to hello@meetcursive.com via Resend
 * - Sends confirmation email to the lead via Resend
 * - Returns success/error
 */

import { NextRequest, NextResponse } from 'next/server'

// Email validation regex
const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

interface LeadFormError {
  field: string
  message: string
}

interface LeadData {
  email: string
  firstName?: string
  company?: string
  source: string
  timestamp: string
}

/**
 * Validate lead capture form data
 */
function validateLeadData(data: Record<string, unknown>): { valid: boolean; errors: LeadFormError[] } {
  const errors: LeadFormError[] = []

  // Validate email (required)
  if (!data.email || typeof data.email !== 'string') {
    errors.push({ field: 'email', message: 'Email is required' })
  } else if (!emailRegex.test(data.email.trim())) {
    errors.push({ field: 'email', message: 'Invalid email format' })
  }

  // Validate firstName (optional but if provided, validate length)
  if (data.firstName && typeof data.firstName === 'string') {
    if (data.firstName.trim().length < 1) {
      errors.push({ field: 'firstName', message: 'First name cannot be empty' })
    } else if (data.firstName.trim().length > 100) {
      errors.push({ field: 'firstName', message: 'First name is too long' })
    }
  }

  // Validate company (optional but if provided, validate length)
  if (data.company && typeof data.company === 'string') {
    if (data.company.trim().length > 200) {
      errors.push({ field: 'company', message: 'Company name is too long' })
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}

/**
 * Escape HTML to prevent XSS in email templates
 */
function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  }
  return text.replace(/[&<>"']/g, (char) => map[char])
}

/**
 * Send internal notification email to the team via Resend
 */
async function sendInternalNotification(leadData: LeadData): Promise<void> {
  const resendApiKey = process.env.RESEND_API_KEY
  const emailFrom = process.env.EMAIL_FROM || 'Cursive <noreply@meetcursive.com>'
  const supportEmail = process.env.SUPPORT_EMAIL || 'hello@meetcursive.com'

  if (!resendApiKey) {
    throw new Error('RESEND_API_KEY is not configured')
  }

  const internalEmailHtml = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #333;">New Lead Captured</h2>

      <div style="background: #f7f9fb; border-left: 4px solid #007aff; padding: 16px; margin: 16px 0; border-radius: 4px;">
        <p style="margin: 8px 0;"><strong>Email:</strong> ${escapeHtml(leadData.email)}</p>
        ${leadData.firstName ? `<p style="margin: 8px 0;"><strong>First Name:</strong> ${escapeHtml(leadData.firstName)}</p>` : ''}
        ${leadData.company ? `<p style="margin: 8px 0;"><strong>Company:</strong> ${escapeHtml(leadData.company)}</p>` : ''}
        <p style="margin: 8px 0;"><strong>Source:</strong> ${escapeHtml(leadData.source)}</p>
        <p style="margin: 8px 0;"><strong>Submitted:</strong> ${escapeHtml(leadData.timestamp)}</p>
      </div>

      <p style="color: #666; font-size: 14px; margin-top: 16px;">
        Follow up with this lead at <a href="mailto:${escapeHtml(leadData.email)}">${escapeHtml(leadData.email)}</a>
      </p>

      <hr style="border: none; border-top: 1px solid #ddd; margin: 24px 0;" />

      <p style="color: #999; font-size: 12px; margin: 0;">
        This notification was generated by the Cursive lead capture system.
      </p>
    </div>
  `

  const sourceLabel = leadData.source === 'exit_intent' ? 'Exit Intent Popup' : leadData.source || 'Popup'

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${resendApiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: emailFrom,
      to: supportEmail,
      subject: `New Lead: ${leadData.email}${leadData.company ? ` (${leadData.company})` : ''} - ${sourceLabel}`,
      html: internalEmailHtml,
      reply_to: leadData.email,
    }),
  })

  if (!response.ok) {
    const errorData = await response.json()
    throw new Error(`Failed to send internal notification: ${JSON.stringify(errorData)}`)
  }
}

/**
 * Send confirmation email to the lead via Resend
 */
async function sendLeadConfirmation(leadData: LeadData): Promise<void> {
  const resendApiKey = process.env.RESEND_API_KEY
  const emailFrom = process.env.EMAIL_FROM || 'Cursive <noreply@meetcursive.com>'

  if (!resendApiKey) {
    throw new Error('RESEND_API_KEY is not configured')
  }

  const greeting = leadData.firstName
    ? `Hi ${escapeHtml(leadData.firstName)},`
    : 'Hi there,'

  const confirmationEmailHtml = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #333;">Thanks for Your Interest in Cursive</h2>

      <p style="color: #666; line-height: 1.6;">
        ${greeting}
      </p>

      <p style="color: #666; line-height: 1.6;">
        We received your information and appreciate your interest in Cursive. Our team will be in touch shortly to help you get started.
      </p>

      <div style="background: #f7f9fb; border-left: 4px solid #007aff; padding: 16px; margin: 24px 0; border-radius: 4px;">
        <p style="margin: 0; color: #666;">
          <strong>In the meantime, here's what you can do:</strong>
        </p>
        <ul style="margin: 12px 0; padding-left: 20px; color: #666;">
          <li><a href="https://cal.com/cursive/30min" style="color: #007aff; text-decoration: none;">Book a free AI audit</a> - Get a personalized assessment</li>
          <li><a href="https://meetcursive.com/platform" style="color: #007aff; text-decoration: none;">Explore our platform</a> - See how Cursive identifies your visitors</li>
          <li><a href="https://meetcursive.com/blog" style="color: #007aff; text-decoration: none;">Read our blog</a> - B2B marketing tips and insights</li>
        </ul>
      </div>

      <p style="color: #666; line-height: 1.6;">
        If you have any questions, feel free to reply to this email or reach out at
        <a href="mailto:hello@meetcursive.com" style="color: #007aff; text-decoration: none;">hello@meetcursive.com</a>.
      </p>

      <p style="color: #666; line-height: 1.6;">
        Best regards,<br/>
        The Cursive Team
      </p>

      <hr style="border: none; border-top: 1px solid #ddd; margin: 24px 0;" />

      <p style="color: #999; font-size: 12px; margin: 0;">
        Cursive AI | <a href="https://meetcursive.com" style="color: #007aff; text-decoration: none;">meetcursive.com</a>
      </p>
    </div>
  `

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${resendApiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: emailFrom,
      to: leadData.email,
      subject: 'Thanks for your interest in Cursive',
      html: confirmationEmailHtml,
    }),
  })

  if (!response.ok) {
    const errorData = await response.json()
    console.error('Failed to send lead confirmation email:', errorData)
    // Don't throw here - the internal notification was already sent successfully
  }
}

/**
 * POST handler for lead capture form submissions
 */
export async function POST(request: NextRequest) {
  try {
    // Parse request body
    const body = await request.json()

    // Validate form data
    const validation = validateLeadData(body)
    if (!validation.valid) {
      return NextResponse.json(
        {
          success: false,
          error: 'Validation failed',
          errors: validation.errors,
        },
        { status: 400 }
      )
    }

    // Prepare lead data
    const leadData: LeadData = {
      email: body.email.trim().toLowerCase(),
      firstName: body.firstName ? body.firstName.trim() : undefined,
      company: body.company ? body.company.trim() : undefined,
      source: body.source || 'popup',
      timestamp: body.timestamp || new Date().toISOString(),
    }

    // Send internal notification email to hello@meetcursive.com
    await sendInternalNotification(leadData)

    // Send confirmation email to the lead
    await sendLeadConfirmation(leadData)

    return NextResponse.json({
      success: true,
      message: 'Lead captured successfully',
    })
  } catch (error) {
    console.error('Error capturing lead:', error)

    return NextResponse.json(
      {
        success: false,
        error: 'An error occurred while processing your request. Please try again later.',
      },
      { status: 500 }
    )
  }
}
