import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://meetcursive.com'

  const routes = [
    '',
    '/platform',
    '/services',
    '/pricing',
    '/about',
    '/resources',
    '/blog',
    '/case-studies',
    '/faq',
    '/contact',
    '/demos',
    '/visitor-identification',
    '/audience-builder',
    '/direct-mail',
    '/clean-room',
    '/data-access',
    '/integrations',
    '/intent-audiences',
    // Industries
    '/industries/financial-services',
    '/industries/ecommerce',
    '/industries/media-advertising',
    '/industries/b2b-software',
    '/industries/agencies',
    '/industries/franchises',
    '/industries/home-services',
    '/industries/retail',
    '/industries/education',
    // Blog posts (52 total)
    '/blog/tips-for-using-marketing-audience-data-efficiently',
    '/blog/steps-to-build-an-effective-audience-building-platform',
    '/blog/why-consumer-targeting-data-is-essential-for-brands',
    '/blog/what-to-consider-when-selecting-a-business-data-platform',
    '/blog/understanding-data-driven-retargeting-practices',
    '/blog/guide-to-choosing-a-b2c-data-platform-for-retailers',
    '/blog/how-marketing-data-solutions-can-improve-campaigns',
    '/blog/steps-to-use-a-customer-data-platform-successfully',
    '/blog/how-to-leverage-business-contact-data-for-better-outreach',
    '/blog/guide-to-direct-mail-marketing-automation-for-agencies',
    '/blog/why-audience-segmentation-platforms-are-key-to-marketing',
    '/blog/discover-the-benefits-of-a-consumer-data-platform',
    '/blog/tips-for-finding-data-targeting-solutions-that-work',
    '/blog/how-to-improve-b2b-contact-data-efficiency',
    '/blog/understanding-business-intelligence-data-for-marketing-success',
    '/blog/guide-to-building-an-effective-audience-targeting-platform',
    '/blog/cross-platform-retargeting-strategies-to-explore',
    '/blog/understanding-data-driven-decision-making-in-marketing',
    '/blog/enhancing-data-connectivity-with-crm-integration',
    '/blog/guide-to-completing-contact-records-easily',
    '/blog/real-time-analytics-strategies-for-better-roi-decisions',
    '/blog/using-website-visitor-tracking-for-lead-generation',
    '/blog/steps-to-improve-your-marketing-database-quality',
    '/blog/understanding-marketing-data-privacy-compliance',
    '/blog/boosting-sales-through-anonymous-visitor-conversion',
    '/blog/leveraging-real-time-data-for-efficient-campaigns',
    '/blog/steps-to-safeguard-consumer-data-privacy',
    '/blog/why-scalable-workflows-benefit-agencies',
    '/blog/understanding-the-impact-of-buyer-intent-on-campaigns',
    '/blog/tips-for-improving-crm-integration-workflows',
    '/blog/why-data-quality-matters-in-marketing',
    '/blog/creating-behavioral-audience-segments-easily',
    '/blog/why-crm-integration-is-crucial-for-smooth-operations',
    '/blog/multifactor-audience-segmentation-for-campaign-success',
    '/blog/how-omni-channel-orchestration-aligns-marketing-efforts',
    '/blog/guide-to-setting-up-a-consumer-data-platform',
    '/blog/retargeting-tactics-to-boost-offline-conversions',
    '/blog/buyer-intent-based-audience-segmentation-techniques',
    '/blog/discovering-multi-touchpoint-attribution-benefits',
    '/blog/intent-signal-tracking-for-b2b-marketing',
    '/blog/intent-based-marketing-tactics-for-b2b',
    '/blog/how-marketing-contact-data-can-warm-up-cold-leads',
    '/blog/business-database-platforms-for-b2b-growth',
    '/blog/b2b-data-enrichment-for-better-marketing-outcomes',
    '/blog/direct-mail-audience-data-for-smarter-winter-outreach',
    '/blog/unlocking-business-data-enrichment-for-growth',
    '/blog/cdp-for-small-marketing-teams',
    '/blog/b2b-audience-targeting-explained-for-everyday-brands',
    '/blog/holiday-marketing-data-platform-guide',
    '/blog/what-b2c-database-providers-do-for-busy-retailers',
    '/blog/how-business-contact-data-helps-grow-winter-connections',
    '/blog/audience-targeting-software-anyone-can-understand',
  ]

  return routes.map(route => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route.startsWith('/blog/') ? 'monthly' as const : 'weekly' as const,
    priority: route === '' ? 1.0 : route.startsWith('/blog/') ? 0.6 : 0.8,
  }))
}
